### ISSUE TITLE
Permission denied citation

### ISSUE THREAD

**Issue by ihincks** [duecredit/duecredit#104]
In the [qinfer library](https://github.com/QInfer/python-qinfer) there is a [PR](https://github.com/QInfer/python-qinfer/pull/129) that is adding `duecredit` as a feature. When I install the [PR branch](https://github.com/QInfer/python-qinfer/tree/feature-duecredit) and run duecredit, one of the citations that pops out is an error:

    [4] 2017-04-03 11:16:13,396 [WARNING] DueCredit internal failure while running <function _dump_collector_summary at 0x7fc3c2755aa0>: OSError(13, 'Permission denied'). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:199)

**Comment by yarikoptic** [comment]
thanks for the report!  are you running it within a directory where you have read-write access?  if you could provide a little bit more of information, e.g. cut/paste of the entire specification and output of that duecredit command you ran... may be ran with  env variable  DUECREDIT_LOGLEVEL=DEBUG set?

**Comment by ihincks** [comment]
I set `DUECREDIT_ALLOW_FAIL=yes` to get the output below. It appears that the script does not have sufficient permissions to `~.cache` (this folder has `drwx------ 36 ihincks ihincks` for me).

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-ff473dfe7f06> in <module>()
----> 1 qi.due._dump_collector_summary()

/usr/local/lib/python2.7/dist-packages/duecredit/dueswitch.pyc in _dump_collector_summary(self)
     77         from duecredit.collector import CollectorSummary
     78         due_summary = CollectorSummary(self.__collectors[True])
---> 79         due_summary.dump()
     80 
     81     def __prepare_exit_and_injections(self):

/usr/local/lib/python2.7/dist-packages/duecredit/collector.pyc in dump(self)
    467     def dump(self):
    468         for output in self._outputs:
--> 469             output.dump()
    470 
    471 

/usr/local/lib/python2.7/dist-packages/duecredit/io.pyc in dump(self, tags)
    214                         self.fd.write('\n[{0}] '.format(citation_nr[ek]))
    215                         self.fd.write(get_text_rendering(cit,
--> 216                                                         style=self.style))
    217                         printed_keys.append(ek)
    218             self.fd.write('\n')

/usr/local/lib/python2.7/dist-packages/duecredit/io.pyc in get_text_rendering(citation, style)
    223     entry = citation.entry
    224     if isinstance(entry, Doi):
--> 225         bibtex_rendering = get_bibtex_rendering(entry)
    226         bibtex_citation = copy.copy(citation)
    227         bibtex_citation.set_entry(bibtex_rendering)

/usr/local/lib/python2.7/dist-packages/duecredit/io.pyc in get_bibtex_rendering(entry)
    235 def get_bibtex_rendering(entry):
    236     if isinstance(entry, Doi):
--> 237         return BibTeX(import_doi(entry.doi))
    238     elif isinstance(entry, BibTeX):
    239         return entry

/usr/local/lib/python2.7/dist-packages/duecredit/io.pyc in import_doi(doi, sleep, retries)
     68         cache_dir = dirname(cached)
     69         if not exists(cache_dir):
---> 70             os.makedirs(cache_dir)
     71         with open(cached, 'w') as f:
     72             if PY2:

/usr/lib/python2.7/os.pyc in makedirs(name, mode)
    155         if tail == curdir:           # xxx/newdir/. exists if xxx/newdir exists
    156             return
--> 157     mkdir(name, mode)
    158 
    159 def removedirs(name):

OSError: [Errno 13] Permission denied: '/home/ihincks/.cache/duecredit/bibtex/10.1126'
```

**Comment by ihincks** [comment]
The above code was run in jupyter notebook (in a folder with write permissions) using the code:

    import os
    os.environ['DUECREDIT_ENABLE'] = 'yes'
    os.environ['DUECREDIT_ALLOW_FAIL'] = 'yes'
    import qinfer as qi
    qi.due._dump_collector_summary()

I get the same warning running with `python -m duecredit test.py` where `test.py` contains only `import qinfer as qi`.

**Comment by yarikoptic** [comment]
so there is something funky with the permissions. anything suspicious "along the path", e.g. run
```shell
uname; p=/home/ihincks/.cache/duecredit/bibtex/10.1126; while [ "$p" != '/' ]; do ls -ld $p || :; p=$(dirname $p); done
```
(NB could do from withing jupyter with `!` prefix)

**Comment by ihincks** [comment]
From jupyter:

```
ihincks
ls: cannot access '/home/ihincks/.cache/duecredit/bibtex/10.1126': No such file or directory
drwxr-xr-x 2 root root 4096 Apr  3 10:30 /home/ihincks/.cache/duecredit/bibtex
drwxr-xr-x 3 root root 4096 Apr  3 10:30 /home/ihincks/.cache/duecredit
drwx------ 36 ihincks ihincks 4096 Apr  3 10:30 /home/ihincks/.cache
drwxr-xr-x 43 ihincks ihincks 4096 Apr  3 13:49 /home/ihincks
drwxr-xr-x 3 root root 4096 Feb 21 19:32 /home
```

**Comment by yarikoptic** [comment]
so, I guess, at some point you have ran the analysis script with DUECREDIT_ENABLE via sudo, which generated all those directories... not sure if we should somehow guard against such invocations because they could as well be very well intended or may be indeed look out for `SUDO_USER` env variable and its valuable to be different from `USER` and avoid enabling duecredit in such a mode (unless some kind of additional switch is enabled)... but not sure yet

**Comment by ihincks** [comment]
Agreed, when I delete the folder in question, the problem is fixed. 

However, I believe the folder is being created during installation, which I do as root.

    sudo pip uninstall duecredit
    sudo rm -r ~/.cache/duecredit/
    sudo pip install duecredit

I get the same behaviour installing from source with `sudo python setup.py install'.

**Comment by ihincks** [comment]
I guess a hacky fix would be to tell setup.py to delete the folder near the end...I don't know enough about setuptools to debug this for real.

**Comment by yarikoptic** [comment]
1. You are correct! `~/.cache/duecredit/bibtex/` got created when I ran `pip install duecredit`.  We should get it fixed!
2. my 1c: do not use pip via sudo ;)

**Comment by ihincks** [comment]
Haha, I agree with your 1c, but I'm too lazy to change my ways.

**Comment by yarikoptic** [comment]
I am lazy (or busy?) too...  some times it takes a few heavy bites from something unpleasant until you realize that half of your flesh is missing ;) 
while at it -- my other 1c:  use `virtualenv` whenever you want/need to setup something via pip .
