### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by yarikoptic** [duecredit/duecredit#119]
Discovered while testing unrelated #118 changes"
```
        if not bibtex.startswith('@'):
            raise ValueError('Query %(url)s for BibTeX for a DOI %(doi)s (wrong doi?) has failed. '
                             'Response code %(status_code)d. '
                             #'BibTeX response was: %(bibtex)s'
>                            % locals())
E           ValueError: Query http://dx.doi.org/10.5281/zenodo.60847 for BibTeX for a DOI 10.5281/zenodo.60847 (wrong doi?) has failed. Response code 500.
```
so should be fixed, probably through mocking that test to not use dx.doi at all for that test

**Comment by mslw** [comment]
After the test ran successfully on my local computer (before making any changes) I tried to re-run Travis job 358, but only got job error - hope that doesn't make too much mess in the records.

For mocking the test (and more details), see the pull request above.
