### ISSUE TITLE
How to cite duecredit?

### ISSUE THREAD

**Issue by sdruskat** [duecredit/duecredit#157]
Very meta, but I'd like to know how to cite duecredit in a paper.
Perhaps consider adding a [CITATION.cff](https://citation-file-format.github.io/) file?

**Comment by yarikoptic** [comment]
Thank you for the issue. I will close when we address it fully. Meanwhile, quickly enabled zenodo for it, so https://zenodo.org/record/3376261 should provide the citation to use.

**Comment by sdruskat** [comment]
Perfect, thanks! If possible, it'd be great to replace @emirvine's screen name with his real name in the Zenodo metadata to enable better creditability.

**Comment by yarikoptic** [comment]
Yes, I will compose proper zenodo.json later on

**Comment by yarikoptic** [comment]
FWIW .zenodo.json was created in 174502eee30693236aa6f87195aa01726f5d99d9 (0.7.0-22-g174502e), so will close this issue

**Comment by yarikoptic** [comment]
FWIW, 0.8.0 entry on zenodo has it all nice: https://zenodo.org/record/3661130#.XkFvG3VOmk8
