### ISSUE TITLE
DueCredit `cite()` doesn't work and `dcite()` works, but not always

### ISSUE THREAD

**Issue by marcelzwiers** [duecredit/duecredit#188]
I added a `due.py` stub-file and these lines to my `__init__.py` file:
```python
from .due import due, Doi

# Register the BIDScoin citation
due.cite(Doi('10.3389/fninf.2021.770608'), description='A versatile toolkit to convert source data to the Brain Imaging Data Structure (BIDS)', path='bidscoin', version=__version__)
```
However, depending on which function I run and on how I run it, I get different results in the duecredit report, i.e. some external tools always get cited, but the tools in bidscoin are sometimes included, but sometimes not (but the __init__.py is always imported in the tools). I know this is a vague issue report, but it's also vague to me...

**Comment by marcelzwiers** [comment]
Ok, I got a little further, I discovered that if a @due.dcite() decorator is somewhere on the codepath, then it all works. If I only use due.cite() then it doesn't work

**Comment by yarikoptic** [comment]
that's odd, will need to debug that I guess :-/

**Comment by marcelzwiers** [comment]
Mhhh, I now think that `cite()` never worked in the first place and that `dcite()` works or not, depending on the existing pickle data. It's a bit complicated, so here's how to reproduce (it took me ages to figure this out). Create `testactivate.py`:
```python
#!/usr/bin/env python3

import sys
from duecredit import due, Doi

def activate_cite():
    due.cite(Doi('10.3389/fninf.2021.770608'), description='Meaning of life', path='question')

def activate_cite_again():
    due.cite(Doi('10.5281/zenodo.3376260'), description='42', path='answer')

@due.dcite(Doi('10.5281/zenodo.3376260'), description='42', path='answer')
def activate_dcite():
    pass

if 'cite' in sys.argv:
    activate_cite()
if 'dcite' in sys.argv:
    activate_dcite()
if 'again' in sys.argv:
    activate_cite_again()
```
Then run:
```console
$ export DUECREDIT_ENABLE=yes
$ chmod a+x test_activate.py
$ ./test_activate.py cite

DueCredit Report:

0 packages cited
0 modules cited
```
So `cite()` didn't work, but `dcite()` works:
```console
$ ./test_activate.py dcite

DueCredit Report:
- 42 / answer (v None) [1]

1 package cited
0 modules cited
0 functions cited

References
----------

[1] Halchenko, Y.O. et al., 2023. duecredit/duecredit: 0.9.2.
```
However, if we create different empty pickle data (but from the same citation) first it no longer works:
```console
$ rm .duecredit.p
$ ./test_activate.py again

DueCredit Report:

0 packages cited
0 modules cited

$ ./test_activate.py dcite

DueCredit Report:

0 packages cited
0 modules cited
```

**Comment by marcelzwiers** [comment]
Ok, it finally dawned on me that using `DUECREDIT_REPORT_ALL=1 duecredit summary` is showing the data that I was expecting before. Hence, in my view, the docs for using `cite()` should come with a very clear warning that these citations won't show up to the user by default. I also think that the last example above should not happen, i.e. that `dcite()` should always overrule `cite()`

**Comment by yarikoptic** [comment]
hm, sorry -- I would need to find some quality time to dive back into this project to get a cleaner understanding on what we expected it to do/behave like.  But if you see how to improve documentation anywhere -- please contribute!
