### ISSUE TITLE
Travis skips tests

### ISSUE THREAD

**Issue by mvdoc** [duecredit/duecredit#25]
Is this what we want?

```
1.92s$ nosetests --with-doctest --with-cov --cover-package duecredit --logging-level=INFO
...................SS..................S.SSSSSS
```

**Comment by yarikoptic** [comment]
On Wed, 29 Jul 2015, Matteo Visconti di Oleggio Castello wrote:

>    Is this what we want?

>  1.92s$ nosetests --with-doctest --with-cov --cover-package duecredit --logging-level=INFO
>  ...................SS..................S.SSSSSS

yeap

run with -v to see which are skipped and why ;)

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by mvdoc** [comment]
ok :)
