### ISSUE TITLE
DUECREDIT_ENABLE doesn't work anymore

### ISSUE THREAD

**Issue by mvdoc** [duecredit/duecredit#45]
Is this just replaced by `python -m duecredit`?

```
(duecredit)contematto@talete ~/github/duecredit/examples (master*) $ DUECREDIT_ENABLE=True python example_scipy.py
I: Simulating 4 blobs
I: Done clustering 4 blobs

(duecredit)contematto@talete ~/github/duecredit/examples (master*) $ python -m duecredit example_scipy.py
I: Simulating 4 blobs
I: Done clustering 4 blobs
DueCredit Report:
- scipy (v 0.14) [1]
  - scipy.cluster.hierarchy:linkage (v 0.14) [2]
- sklearn (v 0.17.dev0) [3]

2 packages cited
0 modules cited
1 functions cited

References
----------

[1] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.
[2] Sibson, R., 1973. SLINK: an optimally efficient algorithm for the single-link cluster method. The Computer Journal, 16(1), pp.30–34.
[3] Pedregosa, F. et al., 2011. Scikit-learn: Machine learning in Python. The Journal of Machine Learning Research, 12, pp.2825–2830.
```

**Comment by yarikoptic** [comment]
Look into that example, it doesn't even import duecredit. That is why it would not know about duecredit even if you set env variable. That is the beauty of the -m due credit approach :-)

On August 12, 2015 7:41:47 PM EDT, Matteo Visconti di Oleggio Castello <notifications@github.com> wrote:
>Is this just replaced by `python -m duecredit`?
>
>```
>(duecredit)contematto@talete ~/github/duecredit/examples (master*) $
>DUECREDIT_ENABLE=True python example_scipy.py
>I: Simulating 4 blobs
>I: Done clustering 4 blobs
>
>(duecredit)contematto@talete ~/github/duecredit/examples (master*) $
>python -m duecredit example_scipy.py
>I: Simulating 4 blobs
>I: Done clustering 4 blobs
>DueCredit Report:
>- scipy (v 0.14) [1]
>  - scipy.cluster.hierarchy:linkage (v 0.14) [2]
>- sklearn (v 0.17.dev0) [3]
>
>2 packages cited
>0 modules cited
>1 functions cited
>
>References
>----------
>
>[1] Jones, E. et al., 2001. SciPy: Open source scientific tools for
>Python.
>[2] Sibson, R., 1973. SLINK: an optimally efficient algorithm for the
>single-link cluster method. The Computer Journal, 16(1), pp.30–34.
>[3] Pedregosa, F. et al., 2011. Scikit-learn: Machine learning in
>Python. The Journal of Machine Learning Research, 12, pp.2825–2830.
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/duecredit/duecredit/issues/45

-- 
Sent from a phone which beats iPhone.

**Comment by mvdoc** [comment]
ha! you changed that example. ok :-)

**Comment by yarikoptic** [comment]
git log and diff must grow into your fingers! :-)

**Comment by mvdoc** [comment]
yes sir! :-)
