### ISSUE TITLE
In PyMVPA, fail to handle failures if lxml, types not available

### ISSUE THREAD

**Issue by mvdoc** [duecredit/duecredit#64]
Might be due to weird setup on discovery?

```
In [1]: from mvpa2.suite import *
2015-12-02 15:44:10,822 [WARNING] DueCredit internal failure while running <function _get_inactive_due at 0x2b59d722d8c0>: ImportError('No module named lxml',). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:73)
2015-12-02 15:44:10,824 [WARNING] DueCredit internal failure while running <function _get_active_due at 0x2b59d722d9b0>: ImportError('cannot import name types',). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:73)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-972bf264f2d0> in <module>()
----> 1 from mvpa2.suite import *

/ihome/castello/venv/pymvpa-upstream-2.4.0.1-42-g8ebdeed/lib/python2.7/site-packages/mvpa2/__init__.pyc in <module>()
    178 # Setup duecredit entry for the entire PyMVPA
    179 from .support.due import due, Doi
--> 180 due.cite(
    181     Doi("10.1007/s12021-008-9041-y"),
    182     description="Multivariate pattern analysis of neural data",

AttributeError: 'DueSwitch' object has no attribute 'cite'
```

**Comment by yarikoptic** [comment]
That sucks... It should have not failed even if anything is wrong within duecredit... Will check later today. Thanks

On December 2, 2015 3:45:59 PM EST, Matteo Visconti di Oleggio Castello <notifications@github.com> wrote:
>Might be due to weird setup on discovery?
>
>```
>In [1]: from mvpa2.suite import *
>2015-12-02 15:44:10,822 [WARNING] DueCredit internal failure while
>running <function _get_inactive_due at 0x2b59d722d8c0>: ImportError('No
>module named lxml',). Please report to developers at
>https://github.com/duecredit/duecredit/issues (utils.py:73)
>2015-12-02 15:44:10,824 [WARNING] DueCredit internal failure while
>running <function _get_active_due at 0x2b59d722d9b0>:
>ImportError('cannot import name types',). Please report to developers
>at https://github.com/duecredit/duecredit/issues (utils.py:73)
>---------------------------------------------------------------------------
>AttributeError                            Traceback (most recent call
>last)
><ipython-input-1-972bf264f2d0> in <module>()
>----> 1 from mvpa2.suite import *
>
>/ihome/castello/venv/pymvpa-upstream-2.4.0.1-42-g8ebdeed/lib/python2.7/site-packages/mvpa2/__init__.pyc
>in <module>()
>    178 # Setup duecredit entry for the entire PyMVPA
>    179 from .support.due import due, Doi
>--> 180 due.cite(
>    181     Doi("10.1007/s12021-008-9041-y"),
>    182     description="Multivariate pattern analysis of neural data",
>
>AttributeError: 'DueSwitch' object has no attribute 'cite'
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/duecredit/duecredit/issues/64

-- 
Sent from a phone which beats iPhone.
