### ISSUE TITLE
Referencing articles with no DOI

### ISSUE THREAD

**Issue by arokem** [duecredit/duecredit#74]
Apparently JMLR articles don't have DOIs (or no longer?) :-( 

http://www.crossref.org/jmlr_DOI.html

I might be missing something: is there a way to use `due.cite` with the `stub` in this case?

**Comment by mvdoc** [comment]
hi @arokem,
instead of adding an entry with a Doi, you can add directly a BibTeX entry, for example

```
BibTeX("""
    @article{pedregosa2011scikit,
        title={Scikit-learn: Machine learning in Python},
        author={Pedregosa, Fabian and Varoquaux, Ga{\"e}l and Gramfort,
        Alexandre and Michel, Vincent and Thirion, Bertrand and Grisel,
        Olivier and Blondel, Mathieu and Prettenhofer, Peter and Weiss,
        Ron and Dubourg, Vincent and others},
        journal={The Journal of Machine Learning Research},
        volume={12},
        pages={2825--2830},
        year={2011},
        publisher={JMLR.org}
        }
    """
```

does this help?

**Comment by arokem** [comment]
Yes - it does! That's exactly what I was looking for.

**Comment by arokem** [comment]
https://github.com/uwescience/sklearn-forest-ci/pull/5
