### ISSUE TITLE
zenodo and "unofficial" bibtex entry types

### ISSUE THREAD

**Issue by mvdoc** [duecredit/duecredit#77]
as showed in #76, zenodo's bibtex entries are saved as `@data` entry types, which are unofficial bibtex entries, thus unsupported by citeproc-py (which we use to parse the bibtex into formatted text).

possible workaround is to change `@data` to `@article` only when parsing the text, but remembering the original version when outputting to bibtex. what do you think @yarikoptic ?

**Comment by yarikoptic** [comment]
citeproc-py:  https://github.com/brechtm/citeproc-py/issues/67
email to crossref folks sent out

**Comment by yarikoptic** [comment]
1. indeed a workaround for now should be `s/@data/@misc` at the point of providing bib entry to citeproc (I don't think `@article` would be the one to use)
2. indeed zenodo itself exports e.g. nipype entry as `@misc`: https://zenodo.org/record/50186/export/hx#.Vynwamcl9OI

**Comment by yarikoptic** [comment]
additional reference:  https://github.com/datacite/content-resolver/issues/4#issuecomment-216875280 
according to which we might want to sanitize/make custom ID to avoid later bibtex-unfriendly UUID being used

**Comment by yarikoptic** [comment]
@mvdoc could you provide a workaround (replace @data to @misc upon passing into citeproc) or should I?

**Comment by yarikoptic** [comment]
just that we really should make it work with zenodo DOIs.

**Comment by mvdoc** [comment]
yep i'll do it

**Comment by yarikoptic** [comment]
FWIW -- I wasn't lazy either : https://github.com/datacite/content-resolver/pull/24 ;-)
