### ISSUE TITLE
RFC: either rename "kind" and "level" into some thing more descriptive

### ISSUE THREAD

**Issue by yarikoptic** [duecredit/duecredit#8]
Hi @mvdoc , we should decide either it would stay as is:

- **level** is just a string with some attached semantic on the prefix of it, then we should document/check on given values, or should it may be become differently defined, 
- **kind**  I have recently added to state what kind of reference it is -- canonical reference to the method/implementation, or example use, or educational tutorial

Should we stick to those names or may be there could be better one chosen?
May be "kind"  could simply be refactored into "tags" list, so multiple tags could be provided and we would just have some "semantic" associated with "canonical",  "use", "edu", and the rest might come useful later... 

What do you think?

Anyone else reading -- your input would be valuable!

**Comment by mvdoc** [comment]
I like **tags** better than **kind**. I think that the tricky part might be to come up with a complete semantic that can cover all possible cases in the future.

For **tags**, what about changing *canonical* to *ref*?

And for **level** maybe allow only

- *module*
- *function*
- *class*
- *class_method*
- *data_structure* (?)

what else?

**Comment by yarikoptic** [comment]
yeah -- let it be 'tags' indeed.  We will not figure out possible cases until we start covering them ;-)    
I don't mind 'ref' -- let's stick to it

level -- what would be the meaning for 'class'?  if no methods invoked, it means not used, we wouldn't care... or it might somehow be the same as "module" in terms of grouping -- but indeed we would need to see a use-case to see how valuable that is.  But that makes me think that may be instead of "level" it should be named more descriptively as a  "group" or even better a "namespace" or ...?

data_structure -- what would be a use-case and how would be different/and triggered?

**Comment by mvdoc** [comment]
On Fri, Jul 10, 2015 at 11:23 PM, Yaroslav Halchenko <
notifications@github.com> wrote:

> level -- what would be the meaning for 'class'? if no methods invoked, it
> means not used, we wouldn't care... or it might somehow be the same as
> "module" in terms of grouping -- but indeed we would need to see a use-case
> to see how valuable that is. But that makes me think that may be instead of
> "level" it should be named more descriptively as a "group" or even better a
> "namespace" or ...
>
Hmm, if we step back, we want to give due credit to certain methods
(algorithms) and software packages. But packages can implement modules
inspired from elsewhere. Probably then we just need to specify these
levels: functions (or methods), modules, and packages, to follow python's
structure.

> data_structure -- what would be a use-case and how would be different/and
> triggered?
>
I was just thinking that if a new method implements a new data structure
(which I don't know how likely it is :-P), then that wouldn't fall into the
other categories. But it's very unlikely that is going to be used on second
thought.

**Comment by yarikoptic** [comment]
On Sat, 11 Jul 2015, Matteo Visconti di Oleggio Castello wrote:
>    > to see how valuable that is. But that makes me think that may be instead
>    of
>    > "level" it should be named more descriptively as a "group" or even
>    better a
>    > "namespace" or ...

>    Hmm, if we step back, we want to give due credit to certain methods
>    (algorithms) and software packages. But packages can implement modules
>    inspired from elsewhere. Probably then we just need to specify these
>    levels: functions (or methods), modules, and packages, to follow python's
>    structure.

rright, so pretty much again, either "namespace" or "level" which would
give us the hierarchy determining to which higher level (module or
package) cited functionality belongs

your comment also inspired a possible additional tag, which could be
"original", or reincarnated "canonical" (in addition to "ref"), which
would signal that it is the "original" implementation by the method's
authors.  Unlike someone else implementing the method (e.g. in our case
implementation of Seltzer's stat assessment in PyMVPA is "ref" but not
"original")?

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik
